### PR TITLE
Change default rng to Xoshiro

### LINKED ISSUE #52: Change default RNG to Xoshiro
Random nodes need to maintain their own random state.

Currently the default rng is `MersenneTwister`, but using `Xoshiro` would be faster, and consistent with Julia's default choice in recent times.

### PR DESCRIPTION
**Pull request by tpgillam**
Closes #52

### CODE REVIEW

**Comment by tpgillam** [comment]
This builds on top of #55

**Comment by willtebbutt** [comment]
Hmmm looks like 1.6 didn't have Xoshiro. Would it make sense to make a deep copy of whatever the default RNG is, or something like that?

**Comment by tpgillam** [comment]
> Hmmm looks like 1.6 didn't have Xoshiro. Would it make sense to make a deep copy of whatever the default RNG is, or something like that?

Yeah indeed... so I've been doing a little digging, trying to work out what the default generator actually was in 1.6. I'm tempted to put in a switch on `VERSION` to handle this.

I don't think we can copy, as the global rng in 1.7 actually isn't an object of type `Xoshiro`... there seems to be another implementation for the task-local RNG.

The default in 1.6 was `MersenneTwister`, so I'll add a workaround.

**Comment by tpgillam** [comment]
> Do you know what buttons I need to press to get it into that state? 

... I changed the "base branch" of the PR to something else, and then back to `main` again, which seemed to do the trick...

This article was vaguely useful https://blog.logrocket.com/using-stacked-pull-requests-in-github/

**Review by willtebbutt — APPROVED** [review]
LGTM -- a definite improvement over what we had previously, so should be merged.

**Pull request merged**
